Remove duplicated keywword
crates.io does not accept more than 5 keywords anymore, which caused my
release to fail:

	error: failed to publish to registry at https://crates.io

	Caused by:
	  the remote server responded with an error: invalid upload request: invalid length 6, expected at most 5 keywords per crate at line 1 column 2001